---
- name: insatll using fact
  hosts: all
  become: yes
  tasks:
    - name: installing Fact
      yum: 
       name: httpd 
       state: absent
      when: ansible_facts['os_family'] == "RedHat"
     
