---
- name: creating users with help of loop
  hosts: pc1
  become: yes
  tasks:
    - name: loops for multipal-users
      user:
        name: "{{item}}"
        state: present
      loop:
        - dhruv
        - mitu
        - mirav  
